### ISSUE TITLE
Error: The tenant 'default' is not accessible 

### ISSUE THREAD

**Issue by msomp** [freddydk/AL-Go-PTE#1]
Hi Freddy,

I'am trying to setup a Test Environment to make first experiences with running CI/CD and AL-Go.
Everything works fine with GitHub runner, but with selfhosted runner the Run Pipeline always exits with the Error: The tenant 'default' is not accessible. The error occurs after creating the container in the compile section.

Maybe you can help me to proceed, thank you.
Martin.

```
   _____                _   _                               _        _                 
  / ____|              | | (_)                             | |      (_)                
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |   
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                     __/ |                                             
                                    |___/                                              

BcContainerHelper is version 4.0.7-dev
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Pro - 22H2
Docker Client Version is 20.10.20
Docker Server Version is 20.10.20
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Image my:sandbox-21.1.48363.49437-at-mt already exists
Using image my:sandbox-21.1.48363.49437-at-mt
Creating Container bc3479583491
Style: sandbox
Multitenant: Yes
Version: 21.1.48363.49437
Platform: 21.0.48357.49418
Generic Tag: 1.0.2.13
Container OS Version: 10.0.20348.1249 (ltsc2022)
Host OS Version: 10.0.22621.819 (22H2)
Using process isolation
Using locale de-AT
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Additional Parameters:
--volume "C:\NAV\actions-runner\_work\ALGOTEST2\ALGOTEST2\:c:\sources"
--env customNavSettings=EnableTaskScheduler=False
Files in C:\ProgramData\BcContainerHelper\Extensions\bc3479583491\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc3479583491 from image my:sandbox-21.1.48363.49437-at-mt
c0a986fb996669da5e8b568cafb9809e0b4d4bdc1ba022c6c229a02802859199
Waiting for container bc3479583491 to be ready
Initializing...
Setting host.docker.internal to 192.168.2.19 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.2.19 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.26.80.1 in container hosts file
Starting Container
Hostname is bc3479583491
PublicDnsName is bc3479583491
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint DF7A9777CCA9F1D8E93DC551224CD6B284994637
DNS identity bc3479583491
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to False
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer without SSL
Update configuration: navsettings.json
Done Configuring Web Client
Enabling Financials User Experience
Dismounting Tenant
Mounting Tenant
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.26.83.161
Container Hostname  : bc3479583491
Container Dns Name  : bc3479583491
Web Client          : http://bc3479583491/BC/?tenant=default
Dev. Server         : http://bc3479583491
Dev. ServerInstance : BC
Dev. Server Tenant  : default
Setting bc3479583491 to 172.26.83.161 in host hosts file
Setting bc3479583491-default to 172.26.83.161 in host hosts file
Setting bc3479583491-default to 172.26.83.161 in container hosts file

Files:
http://bc3479583491:8080/ALLanguage.vsix

Container Total Physical Memory is 31.7Gb
Container Free Physical Memory is 11.6Gb

Initialization took 51 seconds
Ready for connections!
Reading CustomSettings.config from bc3479583491
Creating Desktop Shortcuts for bc3479583491
Container bc3479583491 successfully created
Health check returns False, restarting container
Removing Session bc3479583491
bc3479583491
Waiting for container bc3479583491 to be ready

Initializing...
Setting host.docker.internal to 192.168.2.19 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.2.19 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.26.80.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is bc3479583491
PublicDnsName is bc3479583491
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Container IP Address: 172.26.84.129
Container Hostname  : bc3479583491
Container Dns Name  : bc3479583491
Web Client          : http://bc3479583491/BC/?tenant=default
Dev. Server         : http://bc3479583491
Dev. ServerInstance : BC
Dev. Server Tenant  : default
Setting bc3479583491 to 172.26.84.129 in host hosts file
Setting bc3479583491-default to 172.26.84.129 in host hosts file
Setting bc3479583491-default to 172.26.84.129 in container hosts file

Files:
http://bc3479583491:8080/ALLanguage.vsix

Container Total Physical Memory is 31.7Gb
Container Free Physical Memory is 12.8Gb

Initialization took 10 seconds
Ready for connections!

Use:
Get-BcContainerEventLog -containerName bc3479583491 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName bc3479583491 to get debug information about the container
Enter-BcContainer -containerName bc3479583491 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName bc3479583491 to remove the container again
docker logs bc3479583491 to retrieve information about URL's again

Creating container took 82 seconds
##[endgroup]
##[group]Resolving dependencies

 _____                _       _                   _                           _                 _          
|  __ \              | |     (_)                 | |                         | |               (_)         
| |__) |___ ___  ___ | |_   ___ _ __   __ _    __| | ___ _ __   ___ _ __   __| | ___ _ __   ___ _  ___ ___ 
|  _  // _ \ __|/ _ \| \ \ / / | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '_ \ / _` |/ _ \ '_ \ / __| |/ _ \ __|
| | \ \  __\__ \ (_) | |\ V /| | | | | (_| | | (_| |  __/ |_) |  __/ | | | (_| |  __/ | | | (__| |  __\__ \
|_|  \_\___|___/\___/|_| \_/ |_|_| |_|\__, |  \__,_|\___| .__/ \___|_| |_|\__,_|\___|_| |_|\___|_|\___|___/
                                       __/ |            | |                                                
                                      |___/             |_|                                                

Sorted App folders
- C:\NAV\actions-runner\_work\ALGOTEST2\ALGOTEST2\AlGoBaby
External dependencies
- 437dbf0e-84ff-417a-965d-ed2bb9650972:Microsoft_Base Application_19.0.0.0.app
- 63ca2fa4-4f03-4f2b-a480-172fef340d3f:Microsoft_System Application_19.0.0.0.app
Sorted TestApp folders
- None
##[endgroup]
##[group]Compiling apps

   _____                      _ _ _                                     
  / ____|                    (_) (_)                                    
 | |     ___  _ __ ___  _ __  _| |_ _ __   __ _    __ _ _ __  _ __  ___ 
 | |    / _ \| '_ ` _ \| '_ \| | | | '_ \ / _` |  / _` | '_ \| '_ \/ __|
 | |____ (_) | | | | | | |_) | | | | | | | (_| | | (_| | |_) | |_) \__ \
  \_____\___/|_| |_| |_| .__/|_|_|_|_| |_|\__, |  \__,_| .__/| .__/|___/
                       | |                 __/ |       | |   | |        
                       |_|                |___/        |_|   |_|        

Using Version 1.0.3.0

Compiling C:\NAV\actions-runner\_work\ALGOTEST2\ALGOTEST2\AlGoBaby
Using Symbols Folder: C:\NAV\actions-runner\_work\ALGOTEST2\ALGOTEST2\.packages
The tenant 'default' is not accessible.

Exception Script Stack Trace:
at <ScriptBlock>, <No file>: line 2

PowerShell Call Stack:
bei Invoke-ScriptInBcContainer, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Zeile 71
bei Compile-AppInBcContainer, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Compile-AppInNavContainer.ps1: Zeile 300
bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 662
bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 1585
bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 1210
bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 1202
bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 763
bei Run-AlPipeline, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 728
bei <ScriptBlock>, C:\NAV\actions-runner\_work\_actions\freddydk\AL-Go-Actions\main\RunPipeline\RunPipeline.ps1: Zeile 344
bei <ScriptBlock>, C:\NAV\actions-runner\_work\_temp\8bd6d4bb-3834-433a-bec6-9feefce87aa0.ps1: Zeile 1
bei <ScriptBlock>, <Keine Datei>: Zeile 1

Container Free Physical Memory: 11.3Gb

Services in container bc3479583491:
- MicrosoftDynamicsNavServer$BC is Running
- MSSQL$SQLEXPRESS is Running


Relevant event log from container bc3479583491:
- 20221116 02:09:13 - MicrosoftDynamicsNavServer$BC

  Server instance: BC
  Category: Extensions
  ClientSessionId: d70ccbfa-4686-4475-b036-c4111857de39
  ClientActivityId: d2fc0c25-5f5d-4cc2-94a5-0e8702f04d7e
  ServerSessionUniqueId: 03235af3-bbbd-48fb-ac8b-ed2ce20139e3
  ServerActivityId: 2fac354e-acbd-456c-8ea3-87eb4a09ab61
  EventTime: 11/16/2022 13:09:13
  Message The execution of the code block at GetInstalledNavAppInfo had one or more unhandled exceptions.
  ProcessId: 23852
  Tag: 00000GQ
  ThreadId: 28
  CounterInformation: 
  CustomParameters: {
  }
  GatewayCorrelationId: 1bef05aa-f0bb-4416-a8bc-1180212e1f8e

- 20221116 02:09:13 - MicrosoftDynamicsNavServer$BC

  Server instance: BC
  Category: Runtime
  ClientSessionId: d70ccbfa-4686-4475-b036-c4111857de39
  ClientActivityId: d2fc0c25-5f5d-4cc2-94a5-0e8702f04d7e
  ServerSessionUniqueId: 5c3fda28-8390-4779-8a32-2982902666b5
  ServerActivityId: fe14937e-74b9-4bfb-a316-314ca1bcd048
  EventTime: 11/16/2022 13:09:13
  Message (NavTenantNotAccessibleException): RootException: NavTenantNotAccessibleException
  The tenant 'default' is not accessible.
  CallerStackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavSession.CheckPreconditions(NavTenant tenant, TimeZoneInfo clientTimeZone, NavUserAuthentication navUserAuthentication, Boolean isSystemSession, ConnectionType connectionType)
     at Microsoft.Dynamics.Nav.Runtime.NavSession.Open(Boolean useUserPersonalization, Byte[] licenseToUse, Boolean allowAppsDisabledMode)
     at Microsoft.Dynamics.Nav.Runtime.NavTenant.Microsoft.Dynamics.Nav.Runtime.ITenantSessionHandler.RunTenantActionInSystemSession(Action`2 action, Boolean throwExceptions, Boolean useCurrentCulture, Boolean allowAppsDisabledMode, LanguageSetting language, NavCancellationToken cancellationToken)
     at Microsoft.Dynamics.Nav.Service.NSAdminService.<>c__DisplayClass60_0`1.<RunActionOnRequestedTenant>b__0()
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.<>c__DisplayClass1_0`1.<SendTraceTagOnFailure>b__0()
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.SendTraceTagOnFailure(Action operation, String additionalInfo, Func`2 exceptionMap, String callerName)
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.SendTraceTagOnFailure[T](Func`1 operation, String additionalInfo, Func`2 exceptionMap, String callerName)
     at Microsoft.Dynamics.Nav.Service.NSAdminService.Microsoft.Dynamics.Nav.Types.INCLAdminService.GetInstalledNavAppInfo(String tenantId)
     at SyncInvokeGetInstalledNavAppInfo(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass5_0.<Create>b__0(ServiceOperationContext context)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddToThreadSchedulerCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PartnerTelemetryPermissionErrorCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PushPopCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.<>c__DisplayClass7_0.<PerformanceCounterCombinator>b__0()
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PerformanceCounterCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.InitClientTelemetryIdsCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TlsClearCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
     at System.ServiceModel.Dispatcher.ChannelHandler.DispatchAndReleasePump(RequestContext request, Boolean cleanThread, OperationContext currentOperationContext)
     at System.ServiceModel.Dispatcher.ChannelHandler.HandleRequest(RequestContext request, OperationContext currentOperationContext)
     at System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(IAsyncResult result)
     at System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(IAsyncResult result)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceiveAsyncResult.OnReceive(IAsyncResult result)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.SynchronizedMessageSource.ReceiveAsyncResult.OnReceiveComplete(Object state)
     at System.ServiceModel.Channels.SessionConnectionReader.OnAsyncReadComplete(Object state)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
     at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
     at System.Net.Security.NegotiateStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.NegotiateStream.ReadCallback(AsyncProtocolRequest asyncRequest)
     at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
     at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
     at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.ConnectionStream.IOAsyncResult.OnAsyncIOComplete(Object state)
     at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
     at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
     at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
  
  
  ProcessId: 23852
  Tag: 00001CH
  ThreadId: 28
  CounterInformation: 
  CustomParameters: {
  }
  GatewayCorrelationId: 1bef05aa-f0bb-4416-a8bc-1180212e1f8e

Compile-AppInBcContainer Telemetry Correlation Id: 135a1321-71c2-4cd8-a1aa-e4e080654fa5
##[group]Removing container
Get Event Log from container
Getting event log for bc3479583491
Removing Session bc3479583491
Removing container bc3479583491
Removing entries from hosts
Removing bc3479583491 from container hosts file
Removing bc3479583491-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\bc3479583491
##[endgroup]
Run-AlPipeline Telemetry Correlation Id: adb813bf-9b76-41ff-85af-bba0d23c71e4
##[error]RunPipeline action failed. Error: The tenant 'default' is not accessible. Stacktrace: bei Invoke-ScriptInBcContainer, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Zeile 112 bei Compile-AppInBcContainer, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Compile-AppInNavContainer.ps1: Zeile 300 bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 662 bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 1585 bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 1210 bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 1202 bei <ScriptBlock>, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 763 bei Run-AlPipeline, C:\Users\Administrator\AppData\Local\Temp\dd8d79c8-e88a-4751-b84a-77fff6076350\navcontainerhelper-master\AppHandling\Run-AlPipeline.ps1: Zeile 728 bei <ScriptBlock>, C:\NAV\actions-runner\_work\_actions\freddydk\AL-Go-Actions\main\RunPipeline\RunPipeline.ps1: Zeile 344 bei <ScriptBlock>, C:\NAV\actions-runner\_work\_temp\8bd6d4bb-3834-433a-bec6-9feefce87aa0.ps1: Zeile 1 bei <ScriptBlock>, <Keine Datei>: Zeile 1
AL-Go action ran: RunPipeline Telemetry Correlation Id: 9ba3aa29-340d-407a-8694-985ebdceba7d
Removing BcContainerHelper
##[error]Process completed with exit code 1.

```

**Comment by freddydk** [comment]
It looks like the container is restarted - and then the tenant is not ready.
I just got another partner with the same problem, so maybe version 21 is using a bit more time to mount.

I think the right fix for this is in ContainerHelper.

**Comment by freddydk** [comment]
BTW - you should file bugs here: https://github.com/microsoft/AL-Go/issues

**Comment by msomp** [comment]
FYI, maybe there is a multitenancy correlation, because with type onprem it works fine with the latest ContainerHelper 4.0.6. When using sandbox, it currently only works with the dev version.

**Comment by freddydk** [comment]
It's very likely that the problem only occurs with multi-tenancy and therefore you only need the preview of containerhelper for sandbox, thanks for mentioning that
